import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'ne';
  setLanguage: (lang: 'en' | 'ne') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    shop: 'Shop',
    blog: 'Blog',
    gallery: 'Gallery',
    about: 'About',
    contact: 'Contact',
    cart: 'Cart',
    login: 'Login',
    logout: 'Logout',
    search: 'Search',
    wishlist: 'Wishlist',
    support: 'Support',
    english: 'English',
    nepali: 'नेपाली',
    hi: 'Hi',
    signUp: 'Sign Up',
    
    // Hero Section
    megaSale: 'Mega Sale',
    specialOffer: 'Special Offer',
    upTo60Off: 'Up to 60% OFF',
    blackFriday: 'Black Friday',
    exclusiveDeals: 'Exclusive Deals',
    upTo70Off: 'Up to 70% OFF',
    holidaySale: 'Holiday Sale',
    limitedTime: 'Limited Time',
    upTo65Off: 'Up to 65% OFF',
    yearEndClearance: 'Year End Clearance',
    finalChance: 'Final Chance',
    upTo80Off: 'Up to 80% OFF',
    shopNow: 'Shop Now',
    buyNow: 'Buy Now',
    hotDeals: 'Hot Deals of The Day',
    days: 'days',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    
    // Categories
    shopByCategory: 'Shop by Category',
    exploreProducts: 'Explore our wide range of products',
    electronics: 'Electronics',
    clothingFashion: 'Clothing & Fashion',
    homeKitchen: 'Home & Kitchen',
    beautyPersonalCare: 'Beauty & Personal Care',
    sportsOutdoors: 'Sports & Outdoors',
    booksStationery: 'Books & Stationery',
    toysGames: 'Toys & Games',
    groceryEssentials: 'Grocery & Essentials',
    items: 'Items',
    
    // Products
    topPicks: 'Top Picks This Week',
    viewAllProducts: 'View All Products',
    addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    price: 'Price',
    quantity: 'Quantity',
    total: 'Total',
    
    // Benefits
    fastDelivery: 'Fast Worldwide Delivery',
    freeShipping: 'Free shipping on orders over $50',
    secureShoppingTitle: '100% Secure Shopping',
    secureShoppingDesc: 'Verified sellers & genuine products',
    customerSupportTitle: '24/7 Customer Support',
    customerSupportDesc: 'Chat, call, or email anytime',
    
    // Deal Section
    holidaySpecial: 'Holiday Special',
    limitedTimeOnly: 'Limited Time Only!',
    grabDeals: 'Grab Deals Now',
    
    // Newsletter
    stayUpdated: 'Stay Updated on Deals',
    joinShoppers: 'Join 50,000+ shoppers for exclusive offers and updates',
    yourEmail: 'Your email address',
    subscribeNow: 'Subscribe Now',
    
    // Product Details
    backToShop: 'Back to Shop',
    reviews: 'Reviews',
    verifiedReviews: 'Verified Reviews',
    loading: 'Loading',
    productNotFound: 'Product not found',
    
    // Cart & Checkout
    yourCart: 'Your Cart',
    emptyCart: 'Your cart is empty',
    continueShopping: 'Continue Shopping',
    checkout: 'Checkout',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    orderTotal: 'Order Total',
    placeOrder: 'Place Order',
    
    // Order Success
    orderSuccess: 'Order Placed Successfully!',
    thankYou: 'Thank you for shopping with us!',
    orderDetails: 'Order Details',
    viewCart: 'View Cart',
    paymentDetails: 'Payment Details',
    
    // Footer
    shopAndLearn: 'Shop & Learn',
    shopAll: 'Shop All',
    latestNews: 'Latest News',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    headOffice: 'Head Office',
    phone: 'Phone',
    newsletter: 'Newsletter',
    subscribeNewsletter: 'Subscribe to get special offers and deals directly to your inbox.',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    returns: 'Returns',
    
    // Shop Page
    ourShop: 'Our Shop',
    exploreWideRange: 'Explore our wide range of authentic products.',
    allProducts: 'All Products',
    showing: 'Showing',
    searchProducts: 'Search products...',
    categories: 'Categories',
    all: 'All',
    subcategories: 'Subcategories',
    allSubcategories: 'All Subcategories',
    noProducts: 'No products found',
    tryDifferentFilter: 'Try adjusting your filters to find what you are looking for.',
    loadingProducts: 'Loading products...',
    
    // Contact Page
    getInTouch: 'Get in Touch',
    loveToHear: 'We\'d love to hear from you. Here is how you can reach us.',
    contactInformation: 'Contact Information',
    phoneNumber: 'Phone Number',
    emailSupport: 'Email Support',
    sendMessage: 'Send us a Message',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailAddress: 'Email Address',
    subject: 'Subject',
    message: 'Message',
    sendMessageBtn: 'Send Message',
    generalInquiry: 'General Inquiry',
    orderStatus: 'Order Status',
    returnsRefund: 'Returns & Refund',
    businessPartnership: 'Business Partnership',
    howCanWeHelp: 'How can we help you?',
    
    // About Page
    connectingCraftsmanship: 'Connecting Nepali Craftsmanship with the World.',
    ourStory: 'Our Story',
    buildingFuture: 'We are building the future of commerce in Nepal.',
    aboutStoryText1: 'Hamro Commerce started with a simple idea: to make high-quality Nepali products accessible to everyone, everywhere. Founded in 2023, we have grown from a small garage operation in Kathmandu to a nationwide platform serving thousands of happy customers.',
    aboutStoryText2: 'We believe in the power of technology to transform lives. By connecting local artisans and businesses directly with consumers, we are cutting out middlemen and ensuring fair prices for everyone.',
    happyCustomers: 'Happy Customers',
    localBrands: 'Local Brands',
    whyChooseUs: 'Why Choose Hamro Commerce?',
    whyChooseUsDesc: 'We stand by our core values to deliver the best shopping experience.',
    missionDriven: 'Mission Driven',
    missionDesc: 'To revolutionize the eCommerce landscape in Nepal by ensuring authenticity, speed, and trust in every transaction.',
    customerFirst: 'Customer First',
    customerFirstDesc: 'We obsess over our customers. From 24/7 support to easy returns, your satisfaction is our top priority.',
    communityFocused: 'Community Focused',
    communityDesc: 'We empower local sellers. Every purchase you make supports a Nepali family and strengthens our economy.',
    meetLeadership: 'Meet the Leadership',
    
    // Blog Page
    ourBlog: 'Our Blog',
    storiesFromNepal: 'Stories, tips, and trends from the heart of Nepal.',
    readMore: 'Read More',
    
    // Cart Page
    shoppingCart: 'Shopping Cart',
    yourCartEmpty: 'Your cart is empty',
    cartEmptyDesc: 'Looks like you haven\'t added anything yet. Explore our top categories and find something you love.',
    startShopping: 'Start Shopping',
    selectAll: 'Select All',
    remove: 'Remove',
    updateQuantity: 'Update Quantity',
    orderSummary: 'Order Summary',
    proceedToCheckout: 'Proceed to Checkout',
    clearCart: 'Clear Cart',
    noItemsSelected: 'No Items Selected',
    selectAtLeastOne: 'Please select at least one item to checkout',
    loadingCart: 'Loading your cart...',
    
    // Checkout Page
    checkoutTitle: 'Checkout',
    shippingInformation: 'Shipping Information',
    fullName: 'Full Name',
    phoneNo: 'Phone Number',
    address: 'Address',
    city: 'City',
    district: 'District',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash On Delivery',
    orderSummaryTitle: 'Order Summary',
    itemsSelected: 'items selected',
    deliveryCharge: 'Delivery Charge',
    free: 'Free',
    placeOrderBtn: 'Place Order',
    processing: 'Processing...',
    pleaseWait: 'Please wait...',

    // Common UI
    searchBtn: 'Search',
    languageLabel: 'Language',
    userLabel: 'User',
    chatWithAi: 'Chat with AI',
    freeShippingTopBar: 'Free Shipping on Orders $50+',
    summerSaleTopBar: 'Up to 40% Off Summer Sale',
    warrantyTopBar: '2 Years Warranty',
    viewDetails: 'View Details',
    removeFromWishlist: 'Remove from Wishlist',
    addToWishlist: 'Add to Wishlist',
    addedToWishlistTitle: 'Added to Wishlist',
    addedToWishlistMessageSuffix: 'has been added to your wishlist',
    removedFromWishlistTitle: 'Removed from Wishlist',
    removedFromWishlistMessageSuffix: 'has been removed from your wishlist',
    alreadyInWishlistTitle: 'Already in Wishlist',
    alreadyInWishlistMessage: 'This product is already in your wishlist',
    addedToCartTitle: 'Added to Cart',
    addedToCartMessageSuffix: 'has been added to your cart',
    alreadyInCartTitle: 'Already in Cart',
    alreadyInCartMessage: 'This product is already in your cart',
    loginRequiredTitle: 'Login Required',
    loginRequiredCartMessage: 'Please login to add products to cart',
    loginRequiredWishlistMessage: 'Please login to manage your wishlist',
    errorTitle: 'Error',
    addToCartFailedMessage: 'Failed to add product to cart. Please try again.',
    wishlistUpdateFailedMessage: 'Failed to update wishlist. Please try again.',
    only: 'Only',
    left: 'left',
    aiAssistantTitle: 'Hamro AI Assistant',
    aiAssistantSubtitle: 'Powered by Gemini',
    aiAssistantGreeting: 'Namaste! Welcome to Hamro Commerce. How can I help you find the perfect product today?',
    aiAssistantPlaceholder: 'Ask about products, shipping...',
    footerTagline: 'Your trusted partner for online shopping in Nepal. We bring authentic local products and global brands right to your doorstep.',
    addressLine: 'New Baneshwor, Kathmandu',
    countryNepal: 'Nepal',
    officeHours: 'Mon-Fri, 9AM-6PM',
    wishlistLoading: 'Loading wishlist...',
    wishlistEmptyTitle: 'Your Wishlist is Empty',
    wishlistEmptyDesc: 'Save favorites here and build your own curated shelf.',
    myWishlist: 'My Wishlist',
    itemsSavedForYou: 'saved for you',
    yourFavorites: 'Your Favorites',
    curatedPicks: 'Curated picks',
    item: 'item',
    product: 'Product',
    unitsAvailable: 'units available',
    currentlyUnavailable: 'Currently unavailable',
    outShort: 'OUT',
    addShort: 'ADD',
    galleryTitle: 'Our Gallery',
    gallerySubtitle: 'Visual stories from the land of Himalayas.',
    viewLarger: 'View Larger',
    galleryEmpty: 'More images coming soon to this category.',
    close: 'Close',
    galleryAllLabel: 'All Gallery',
    galleryAllTagline: 'Hamro Nepal, Hamro Gaurav',
    galleryAllDesc: 'A glimpse into the heart and soul of Nepal through our products and people.',
    galleryTraditionalLabel: 'Traditional & Cultural',
    galleryTraditionalTagline: 'Hamro pahichaan, hamrai parampara',
    galleryTraditionalDesc: 'Products that carry the soul of Nepal: Dhaka topi, Gunyu-cholo, and more.',
    galleryHandmadeLabel: 'Handmade & Artisanal',
    galleryHandmadeTagline: 'Ghar-ghar ko kunai haat ko kalakarita',
    galleryHandmadeDesc: 'Products made with love, hard work, and creativity by local artisans.',
    gallerySpiritualLabel: 'Spiritual & Religious',
    gallerySpiritualTagline: 'Astha, shanti ra dharma ko sparsha',
    gallerySpiritualDesc: 'Rudraksha, Singing bowls, and items filled with faith and devotion.',
    galleryFoodsLabel: 'Traditional Foods',
    galleryFoodsTagline: 'Gau-thalo ko swad, sanskriti ko mithas',
    galleryFoodsDesc: 'The authentic taste of home: Gundruk, Himalayan tea, and local spices.',
    galleryFestiveLabel: 'Festive & Rituals',
    galleryFestiveTagline: 'Parba-parva le bhitraune samjhina ra utsav',
    galleryFestiveDesc: 'Celebrating Dashain, Tihar, and the vibrant colors of our festivals.',
    galleryEthnicLabel: 'Ethnic Wear',
    galleryEthnicTagline: 'Riti-rivaaj, pahichaan, rangin Nepal',
    galleryEthnicDesc: 'Celebrating Nepal\'s diversity with Haku patasi, Bakhu, and ethnic jewelry.',
    galleryOrganicLabel: 'Organic & Natural',
    galleryOrganicTagline: 'Himal ko sampada, prakritiko upahar',
    galleryOrganicDesc: 'Pure products from Nepal\'s land: Herbal soaps, essential oils, and honey.',
    galleryGiftsLabel: 'Cultural Gifts',
    galleryGiftsTagline: 'Hamro sanskriti ko upahaar',
    galleryGiftsDesc: 'Gifts with meaning: Khukuri, wood carvings, and souvenirs.',
    galleryImageDhakaTopi: 'Classic Dhaka Topi',
    galleryImageNepaliTradition: 'Nepali Tradition',
    galleryImageNepaliArchitecture: 'Nepali Architecture',
    galleryImageWoodCarving: 'Wood Carving',
    galleryImageYakWoolShawl: 'Yak Wool Shawl',
    galleryImageTempleSerenity: 'Temple Serenity',
    galleryImagePrayerFlags: 'Prayer Flags',
    galleryImageBuddhaStatue: 'Buddha Statue',
    galleryImageMarketSpices: 'Market Spices',
    galleryImageIlamTeaGarden: 'Ilam Tea Garden',
    galleryImageHimalayanHoney: 'Himalayan Honey',
    galleryImageDashainTika: 'Dashain Tika',
    galleryImageFestivalLights: 'Festival Lights',
    galleryImageTraditionalAttire: 'Traditional Attire',
    galleryImageDauraSuruwal: 'Daura Suruwal',
    galleryImageCulturalMusicians: 'Cultural Musicians',
    galleryImageHimalayanHerbs: 'Himalayan Herbs',
    galleryImageOrganicProducts: 'Organic Products',
    galleryImageKhukuriGift: 'Khukuri Gift',
    galleryImageSouvenirShop: 'Souvenir Shop',
    galleryImageCulturalGifts: 'Cultural Gifts',
    testimonialsBadge: 'TESTIMONIALS',
    testimonialsTitle: 'What Our Customers Say',
    testimonialsSubtitle: 'Real feedback from people who shop with us.',
    testimonialsEmptyTitle: 'No Testimonials Yet',
    testimonialsEmptyDesc: 'Check back later for customer stories.',
    cartBlankTitle: 'Your Cart is a Blank Canvas',
    cartBlankDesc: 'It seems you haven\'t discovered your next favorite item yet. Explore our curated collections and start your journey.',
    yourSelection: 'Your Selection',
    secureCheckout: 'Secure Checkout',
    deselectAll: 'Deselect All',
    handcraftedLabel: 'Handcrafted',
    colorLabel: 'Color',
    sizeLabel: 'Size',
    itemTotal: 'Item Total',
    premiumQuality: 'PREMIUM QUALITY',
    estimatedTax: 'Estimated Tax',
    included: 'Included',
    totalAmount: 'Total Amount',
    vatIncluded: 'VAT & Service charges included.',
    purchaseProtection: 'Purchase Protection',
    dataEncrypted: 'Your data is fully encrypted',
    expressDelivery: 'Express Delivery',
    quickShipping: 'Quickest possible shipping time',
    blogsEmptyTitle: 'No blogs available at the moment',
    blogsEmptyDesc: 'Check back later for new content',
    blogNotFound: 'Blog not found',
    blogLoadError: 'Failed to load blog. Please try again.',
    blogNotFoundDesc: 'The blog you\'re looking for doesn\'t exist or has been removed.',
    backToBlogs: 'Back to Blogs',
    editorialLabel: 'Editorial',
    minRead: 'min read',
    keyTakeaway: 'Key takeaway',
    readingGuide: 'Reading guide',
    readingGuideDesc: 'Best enjoyed with a warm drink and a slow scroll.',
    moreLikeThis: 'More Like This',
    picks: 'picks',
    contactHeroTitle: 'Contact Our Team',
    contactHeroSubtitle: 'Have questions about our products or services? We\'re here to help. Reach out to us through any of the channels below.',
    onlineSupport: 'Online Support',
    email: 'Email',
    location: 'Location',
    contactOfficeHours: 'Sun - Fri, 10am - 6pm',
    contactCity: 'Kawasoti, Nawalpur',
    contactArea: 'Main Market Area',
    messageSentSuccess: 'Message sent successfully! We\'ll get back to you soon.',
    sending: 'Sending...',
    quickResponseTitle: 'Quick Response',
    quickResponseDesc: 'Replies within 24 hours',
    secureCommunicationTitle: 'Secure Communication',
    secureCommunicationDesc: 'Your data is protected',
    nationwideSupportTitle: 'Nationwide Support',
    nationwideSupportDesc: 'Serving all of Nepal',
    expertGuidanceTitle: 'Expert Guidance',
    expertGuidanceDesc: 'Dedicated support team',
    contactFooter: '© 2026 Hamro Commerce • Kawasoti, Nawalpur',
  },
  ne: {
    // Navigation
    home: 'गृहपृष्ठ',
    shop: 'पसल',
    blog: 'ब्लग',
    gallery: 'ग्यालेरी',
    about: 'बारेमा',
    contact: 'सम्पर्क',
    cart: 'कार्ट',
    login: 'लगइन',
    logout: 'लगआउट',
    search: 'खोज्नुहोस्',
    wishlist: 'इच्छा सूची',
    support: 'समर्थन',
    english: 'English',
    nepali: 'नेपाली',
    hi: 'नमस्ते',
    signUp: 'साइन अप',
    
    // Hero Section
    megaSale: 'मेगा बिक्री',
    specialOffer: 'विशेष प्रस्ताव',
    upTo60Off: '६०% सम्म छुट',
    blackFriday: 'ब्ल्याक फ्राइडे',
    exclusiveDeals: 'विशेष सम्झौता',
    upTo70Off: '७०% सम्म छुट',
    holidaySale: 'छुट्टी बिक्री',
    limitedTime: 'सीमित समय',
    upTo65Off: '६५% सम्म छुट',
    yearEndClearance: 'वर्ष अन्त्य क्लियरेन्स',
    finalChance: 'अन्तिम मौका',
    upTo80Off: '८०% सम्म छुट',
    shopNow: 'अहिले किन्नुहोस्',
    buyNow: 'अहिले किन्नुहोस्',
    hotDeals: 'आजको तातो सौदा',
    days: 'दिन',
    hours: 'घण्टा',
    minutes: 'मिनेट',
    seconds: 'सेकेन्ड',
    
    // Categories
    shopByCategory: 'श्रेणी अनुसार किनमेल',
    exploreProducts: 'हाम्रो उत्पादनहरूको विस्तृत श्रृंखला अन्वेषण गर्नुहोस्',
    electronics: 'इलेक्ट्रोनिक्स',
    clothingFashion: 'कपडा र फेसन',
    homeKitchen: 'घर र भान्सा',
    beautyPersonalCare: 'सौन्दर्य र व्यक्तिगत हेरचाह',
    sportsOutdoors: 'खेलकुद र बाहिरी',
    booksStationery: 'किताब र स्टेशनरी',
    toysGames: 'खेलौना र खेल',
    groceryEssentials: 'किराना र आवश्यक सामान',
    items: 'वस्तुहरू',
    
    // Products
    topPicks: 'यस हप्ताको शीर्ष छनोट',
    viewAllProducts: 'सबै उत्पादनहरू हेर्नुहोस्',
    addToCart: 'कार्टमा थप्नुहोस्',
    outOfStock: 'स्टकमा छैन',
    inStock: 'स्टकमा छ',
    price: 'मूल्य',
    quantity: 'परिमाण',
    total: 'जम्मा',
    
    // Benefits
    fastDelivery: 'छिटो विश्वव्यापी डेलिभरी',
    freeShipping: '$५० भन्दा बढी अर्डरमा निःशुल्क ढुवानी',
    secureShoppingTitle: '१००% सुरक्षित किनमेल',
    secureShoppingDesc: 'प्रमाणित विक्रेता र वास्तविक उत्पादन',
    customerSupportTitle: '२४/७ ग्राहक समर्थन',
    customerSupportDesc: 'जुनसुकै समय च्याट, कल, वा इमेल गर्नुहोस्',
    
    // Deal Section
    holidaySpecial: 'छुट्टी विशेष',
    limitedTimeOnly: 'सीमित समय मात्र!',
    grabDeals: 'अहिले नै सौदा लिनुहोस्',
    
    // Newsletter
    stayUpdated: 'सम्झौतामा अद्यावधिक रहनुहोस्',
    joinShoppers: 'विशेष प्रस्ताव र अपडेटहरूको लागि ५०,०००+ खरिदकर्तासँग सामेल हुनुहोस्',
    yourEmail: 'तपाईंको इमेल ठेगाना',
    subscribeNow: 'अहिले सदस्यता लिनुहोस्',
    
    // Product Details
    backToShop: 'पसलमा फर्कनुहोस्',
    reviews: 'समीक्षा',
    verifiedReviews: 'प्रमाणित समीक्षाहरू',
    loading: 'लोड हुँदैछ',
    productNotFound: 'उत्पादन भेटिएन',
    
    // Cart & Checkout
    yourCart: 'तपाईंको कार्ट',
    emptyCart: 'तपाईंको कार्ट खाली छ',
    continueShopping: 'किनमेल जारी राख्नुहोस्',
    checkout: 'चेकआउट',
    subtotal: 'उप-योग',
    shipping: 'ढुवानी',
    orderTotal: 'आदेश जम्मा',
    placeOrder: 'आदेश दिनुहोस्',
    
    // Order Success
    orderSuccess: 'आदेश सफलतापूर्वक राखियो!',
    thankYou: 'हामीसँग किनमेल गर्नुभएकोमा धन्यवाद!',
    orderDetails: 'आदेश विवरण',
    viewCart: 'कार्ट हेर्नुहोस्',
    paymentDetails: 'भुक्तानी विवरण',
    
    // Footer
    shopAndLearn: 'किनमेल र सिक्नुहोस्',
    shopAll: 'सबै किन्नुहोस्',
    latestNews: 'ताजा समाचार',
    aboutUs: 'हाम्रो बारेमा',
    contactUs: 'सम्पर्क',
    headOffice: 'प्रधान कार्यालय',
    phone: 'फोन',
    newsletter: 'न्यूजलेटर',
    subscribeNewsletter: 'विशेष प्रस्ताव र सम्झौताहरू सिधै तपाईंको इनबक्समा प्राप्त गर्न सदस्यता लिनुहोस्।',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा सर्तहरू',
    returns: 'फिर्ता',
    
    // Shop Page
    ourShop: 'हाम्रो पसल',
    exploreWideRange: 'हाम्रो प्रामाणिक उत्पादनहरूको विस्तृत श्रृंखला अन्वेषण गर्नुहोस्।',
    allProducts: 'सबै उत्पादनहरू',
    showing: 'देखाउँदै',
    searchProducts: 'उत्पादनहरू खोज्नुहोस्...',
    categories: 'श्रेणीहरू',
    all: 'सबै',
    subcategories: 'उप-श्रेणीहरू',
    allSubcategories: 'सबै उप-श्रेणीहरू',
    noProducts: 'कुनै उत्पादन भेटिएन',
    tryDifferentFilter: 'तपाईंले खोजिरहनुभएको कुरा फेला पार्न आफ्नो फिल्टरहरू समायोजन गर्ने प्रयास गर्नुहोस्।',
    loadingProducts: 'उत्पादनहरू लोड हुँदैछ...',
    
    // Contact Page
    getInTouch: 'सम्पर्कमा रहनुहोस्',
    loveToHear: 'हामी तपाईंबाट सुन्न मन पराउँछौं। यहाँ तपाईं हामीलाई कसरी सम्पर्क गर्न सक्नुहुन्छ।',
    contactInformation: 'सम्पर्क जानकारी',
    phoneNumber: 'फोन नम्बर',
    emailSupport: 'इमेल समर्थन',
    sendMessage: 'हामीलाई सन्देश पठाउनुहोस्',
    firstName: 'पहिलो नाम',
    lastName: 'थर',
    emailAddress: 'इमेल ठेगाना',
    subject: 'विषय',
    message: 'सन्देश',
    sendMessageBtn: 'सन्देश पठाउनुहोस्',
    generalInquiry: 'सामान्य सोधपुछ',
    orderStatus: 'आदेश स्थिति',
    returnsRefund: 'फिर्ता र रिफन्ड',
    businessPartnership: 'व्यापार साझेदारी',
    howCanWeHelp: 'हामी तपाईंलाई कसरी मद्दत गर्न सक्छौं?',
    
    // About Page
    connectingCraftsmanship: 'नेपाली शिल्पकलालाई विश्वसँग जोड्दै।',
    ourStory: 'हाम्रो कथा',
    buildingFuture: 'हामी नेपालमा वाणिज्यको भविष्य निर्माण गर्दैछौं।',
    aboutStoryText1: 'हमरो कमर्स एक सरल विचारबाट सुरु भयो: उच्च-गुणस्तरको नेपाली उत्पादनहरू सबैलाई, जहाँसुकै पहुँचयोग्य बनाउन। २०२३ मा स्थापना भएको, हामी काठमाडौंको एउटा सानो ग्यारेज अपरेशनबाट हजारौं खुसी ग्राहकहरूलाई सेवा दिने राष्ट्रव्यापी प्लेटफर्ममा बढेका छौं।',
    aboutStoryText2: 'हामी जीवन परिवर्तन गर्न प्रविधिको शक्तिमा विश्वास गर्छौं। स्थानीय कारीगर र व्यवसायहरूलाई सीधै उपभोक्ताहरूसँग जोडेर, हामी बिचौलियाहरू हटाउँदैछौं र सबैका लागि उचित मूल्य सुनिश्चित गर्दैछौं।',
    happyCustomers: 'खुसी ग्राहकहरू',
    localBrands: 'स्थानीय ब्रान्डहरू',
    whyChooseUs: 'हमरो कमर्स किन रोज्ने?',
    whyChooseUsDesc: 'हामी उत्कृष्ट किनमेल अनुभव प्रदान गर्न हाम्रो मूल मूल्यहरूमा खडा छौं।',
    missionDriven: 'मिशन संचालित',
    missionDesc: 'प्रत्येक लेनदेनमा प्रामाणिकता, गति र विश्वास सुनिश्चित गरेर नेपालमा ई-कमर्स परिदृश्यमा क्रान्ति ल्याउन।',
    customerFirst: 'ग्राहक पहिले',
    customerFirstDesc: 'हामी हाम्रा ग्राहकहरूको लागि जुनून राख्छौं। २४/७ समर्थनदेखि सजिलो फिर्तासम्म, तपाईंको सन्तुष्टि हाम्रो शीर्ष प्राथमिकता हो।',
    communityFocused: 'समुदाय केन्द्रित',
    communityDesc: 'हामी स्थानीय विक्रेताहरूलाई सशक्त बनाउँछौं। तपाईंले गर्ने प्रत्येक खरिदले नेपाली परिवारलाई समर्थन गर्दछ र हाम्रो अर्थतन्त्रलाई बलियो बनाउँछ।',
    meetLeadership: 'नेतृत्वलाई भेट्नुहोस्',
    
    // Blog Page
    ourBlog: 'हाम्रो ब्लग',
    storiesFromNepal: 'नेपालको मुटुबाट कथाहरू, सुझावहरू र प्रवृत्तिहरू।',
    readMore: 'थप पढ्नुहोस्',
    
    // Cart Page
    shoppingCart: 'किनमेल कार्ट',
    yourCartEmpty: 'तपाईंको कार्ट खाली छ',
    cartEmptyDesc: 'तपाईंले अहिलेसम्म केही थप्नुभएको छैन जस्तो देखिन्छ। हाम्रो शीर्ष श्रेणीहरू अन्वेषण गर्नुहोस् र तपाईंलाई मनपर्ने केही फेला पार्नुहोस्।',
    startShopping: 'किनमेल सुरु गर्नुहोस्',
    selectAll: 'सबै चयन गर्नुहोस्',
    remove: 'हटाउनुहोस्',
    updateQuantity: 'मात्रा अपडेट गर्नुहोस्',
    orderSummary: 'आदेश सारांश',
    proceedToCheckout: 'चेकआउटमा जानुहोस्',
    clearCart: 'कार्ट खाली गर्नुहोस्',
    noItemsSelected: 'कुनै वस्तु चयन गरिएको छैन',
    selectAtLeastOne: 'कृपया चेकआउट गर्न कम्तिमा एउटा वस्तु चयन गर्नुहोस्',
    loadingCart: 'तपाईंको कार्ट लोड हुँदैछ...',
    
    // Checkout Page
    checkoutTitle: 'चेकआउट',
    shippingInformation: 'ढुवानी जानकारी',
    fullName: 'पूरा नाम',
    phoneNo: 'फोन नम्बर',
    address: 'ठेगाना',
    city: 'शहर',
    district: 'जिल्ला',
    paymentMethod: 'भुक्तानी विधि',
    cashOnDelivery: 'डेलिभरीमा नगद',
    orderSummaryTitle: 'आदेश सारांश',
    itemsSelected: 'वस्तुहरू चयन गरियो',
    deliveryCharge: 'डेलिभरी शुल्क',
    free: 'निःशुल्क',
    placeOrderBtn: 'आदेश दिनुहोस्',
    processing: 'प्रशोधन गर्दै...',
    pleaseWait: 'कृपया पर्खनुहोस्...',

    // Common UI
    searchBtn: 'खोज्नुहोस्',
    languageLabel: 'भाषा',
    userLabel: 'प्रयोगकर्ता',
    chatWithAi: 'AI सँग च्याट गर्नुहोस्',
    freeShippingTopBar: '५०$ भन्दा माथि अर्डरमा निःशुल्क ढुवानी',
    summerSaleTopBar: 'समर सेलमा ४०% सम्म छुट',
    warrantyTopBar: '२ वर्ष वारेन्टी',
    viewDetails: 'विवरण हेर्नुहोस्',
    removeFromWishlist: 'इच्छा सूचीबाट हटाउनुहोस्',
    addToWishlist: 'इच्छा सूचीमा थप्नुहोस्',
    addedToWishlistTitle: 'इच्छा सूचीमा थपियो',
    addedToWishlistMessageSuffix: 'इच्छा सूचीमा थपियो',
    removedFromWishlistTitle: 'इच्छा सूचीबाट हटाइयो',
    removedFromWishlistMessageSuffix: 'इच्छा सूचीबाट हटाइयो',
    alreadyInWishlistTitle: 'पहिले नै इच्छा सूचीमा',
    alreadyInWishlistMessage: 'यो उत्पादन पहिले नै तपाईंको इच्छा सूचीमा छ',
    addedToCartTitle: 'कार्टमा थपियो',
    addedToCartMessageSuffix: 'तपाईंको कार्टमा थपियो',
    alreadyInCartTitle: 'पहिले नै कार्टमा',
    alreadyInCartMessage: 'यो उत्पादन पहिले नै तपाईंको कार्टमा छ',
    loginRequiredTitle: 'लगइन आवश्यक',
    loginRequiredCartMessage: 'कार्टमा थप्न लगइन गर्नुहोस्',
    loginRequiredWishlistMessage: 'इच्छा सूची व्यवस्थापन गर्न लगइन गर्नुहोस्',
    errorTitle: 'त्रुटि',
    addToCartFailedMessage: 'कार्टमा थप्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।',
    wishlistUpdateFailedMessage: 'इच्छा सूची अद्यावधिक गर्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।',
    only: 'केवल',
    left: 'बाँकी',
    aiAssistantTitle: 'हाम्रो AI सहायक',
    aiAssistantSubtitle: 'Gemini द्वारा संचालित',
    aiAssistantGreeting: 'नमस्ते! हाम्रो कमर्समा स्वागत छ। आज तपाईंलाई उपयुक्त उत्पादन फेला पार्न म कसरी मद्दत गरूँ?',
    aiAssistantPlaceholder: 'उत्पादन, ढुवानी आदि बारे सोध्नुहोस्...',
    footerTagline: 'नेपालमा अनलाइन किनमेलका लागि तपाईंको भरपर्दो साथी। हामी स्थानीय उत्पादन र विश्वव्यापी ब्रान्डहरू तपाईंको ढोकासम्म ल्याउँछौं।',
    addressLine: 'नयाँ बानेश्वर, काठमाडौं',
    countryNepal: 'नेपाल',
    officeHours: 'सोम-शुक्र, बिहान ९ देखि बेलुका ६',
    wishlistLoading: 'इच्छा सूची लोड हुँदैछ...',
    wishlistEmptyTitle: 'तपाईंको इच्छा सूची खाली छ',
    wishlistEmptyDesc: 'आफ्ना मनपर्ने वस्तुहरू यहाँ सेभ गर्नुहोस्।',
    myWishlist: 'मेरो इच्छा सूची',
    itemsSavedForYou: 'तपाईंका लागि सेभ गरिएको',
    yourFavorites: 'तपाईंका मनपर्ने',
    curatedPicks: 'छानिएका छनोटहरू',
    item: 'वस्तु',
    product: 'उत्पादन',
    unitsAvailable: 'युनिट उपलब्ध',
    currentlyUnavailable: 'हाल उपलब्ध छैन',
    outShort: 'स्टक छैन',
    addShort: 'थप्नुहोस्',
    galleryTitle: 'हाम्रो ग्यालरी',
    gallerySubtitle: 'हिमालयको भूमिबाट दृश्य कथाहरू।',
    viewLarger: 'ठूलो हेर्नुहोस्',
    galleryEmpty: 'यो श्रेणीमा थप तस्बिरहरू चाँडै थपिनेछन्।',
    close: 'बन्द गर्नुहोस्',
    galleryAllLabel: 'सबै ग्यालरी',
    galleryAllTagline: 'हाम्रो नेपाल, हाम्रो गौरव',
    galleryAllDesc: 'हाम्रो उत्पादन र समुदायमार्फत नेपालको मन र आत्माको झलक।',
    galleryTraditionalLabel: 'परम्परागत र सांस्कृतिक',
    galleryTraditionalTagline: 'हाम्रो पहिचान, हाम्रो परम्परा',
    galleryTraditionalDesc: 'नेपाली आत्मा बोकेका उत्पादन: ढाका टोपी, गुन्यु-चोलो आदि।',
    galleryHandmadeLabel: 'हातले बनेका र कलात्मक',
    galleryHandmadeTagline: 'घर-घरका हातको कलाकृति',
    galleryHandmadeDesc: 'स्थानीय कारीगरहरूले माया, मेहनत र सिर्जनासँग बनाएका वस्तुहरू।',
    gallerySpiritualLabel: 'आध्यात्मिक र धार्मिक',
    gallerySpiritualTagline: 'आस्था, शान्ति र धर्मको स्पर्श',
    gallerySpiritualDesc: 'रुद्राक्ष, सिंगिङ बाउल र भक्तिभावले भरिएका वस्तुहरू।',
    galleryFoodsLabel: 'परम्परागत खाना',
    galleryFoodsTagline: 'गाउँ-ठाउँको स्वाद, संस्कृतिको मिठास',
    galleryFoodsDesc: 'घरको असली स्वाद: गुन्द्रुक, हिमाली चिया र स्थानीय मसला।',
    galleryFestiveLabel: 'चाडपर्व र विधि',
    galleryFestiveTagline: 'पर्वले भित्र्याउने सम्झना र उत्सव',
    galleryFestiveDesc: 'दशैं, तिहार र हाम्रो चाडपर्वका रङ्गहरू।',
    galleryEthnicLabel: 'जातीय पोशाक',
    galleryEthnicTagline: 'रीतिरिवाज, पहिचान, रंगीन नेपाल',
    galleryEthnicDesc: 'हाकु पटासी, बख्खु र जातीय गहनासहित नेपालको विविधता।',
    galleryOrganicLabel: 'अर्गानिक र प्राकृतिक',
    galleryOrganicTagline: 'हिमालको सम्पदा, प्रकृतिको उपहार',
    galleryOrganicDesc: 'नेपालको माटोबाट शुद्ध वस्तु: जडीबुटी साबुन, तेल र मह।',
    galleryGiftsLabel: 'सांस्कृतिक उपहार',
    galleryGiftsTagline: 'हाम्रो संस्कृतिको उपहार',
    galleryGiftsDesc: 'अर्थपूर्ण उपहार: खुकुरी, काठको नक्काशी र स्मृति वस्तु।',
    galleryImageDhakaTopi: 'क्लासिक ढाका टोपी',
    galleryImageNepaliTradition: 'नेपाली परम्परा',
    galleryImageNepaliArchitecture: 'नेपाली वास्तुकला',
    galleryImageWoodCarving: 'काठको नक्काशी',
    galleryImageYakWoolShawl: 'याक ऊनको सल',
    galleryImageTempleSerenity: 'मन्दिरको शान्ति',
    galleryImagePrayerFlags: 'प्रार्थना झन्डा',
    galleryImageBuddhaStatue: 'बुद्ध प्रतिमा',
    galleryImageMarketSpices: 'बजारका मसला',
    galleryImageIlamTeaGarden: 'इलाम चिया बगान',
    galleryImageHimalayanHoney: 'हिमाली मह',
    galleryImageDashainTika: 'दशैं टीका',
    galleryImageFestivalLights: 'चाडपर्वका बत्तीहरू',
    galleryImageTraditionalAttire: 'परम्परागत पोशाक',
    galleryImageDauraSuruwal: 'दौरा सुरुवाल',
    galleryImageCulturalMusicians: 'सांस्कृतिक संगीतकार',
    galleryImageHimalayanHerbs: 'हिमाली जडीबुटी',
    galleryImageOrganicProducts: 'अर्गानिक उत्पादन',
    galleryImageKhukuriGift: 'खुकुरी उपहार',
    galleryImageSouvenirShop: 'स्मृति पसल',
    galleryImageCulturalGifts: 'सांस्कृतिक उपहार',
    testimonialsBadge: 'प्रशंसापत्र',
    testimonialsTitle: 'ग्राहकहरूले के भन्छन्',
    testimonialsSubtitle: 'हामीसँग किनमेल गर्नेहरूको वास्तविक प्रतिक्रिया।',
    testimonialsEmptyTitle: 'अहिले कुनै प्रशंसापत्र छैन',
    testimonialsEmptyDesc: 'ग्राहक कथाहरूका लागि पछि फेरि हेर्नुहोस्।',
    cartBlankTitle: 'तपाईंको कार्ट खाली छ',
    cartBlankDesc: 'अझै नयाँ मनपर्ने वस्तु फेला परेको छैन। हाम्रो संग्रह हेर्नुहोस् र यात्रा सुरु गर्नुहोस्।',
    yourSelection: 'तपाईंको छनोट',
    secureCheckout: 'सुरक्षित चेकआउट',
    deselectAll: 'सबै चयन हटाउनुहोस्',
    handcraftedLabel: 'हातले बनेको',
    colorLabel: 'रङ',
    sizeLabel: 'साइज',
    itemTotal: 'वस्तुको जम्मा',
    premiumQuality: 'उत्कृष्ट गुणस्तर',
    estimatedTax: 'अनुमानित कर',
    included: 'समावेश',
    totalAmount: 'कुल रकम',
    vatIncluded: 'भ्याट र सेवा शुल्क समावेश।',
    purchaseProtection: 'खरिद सुरक्षा',
    dataEncrypted: 'तपाईंको डेटा पूर्ण रूपमा इन्क्रिप्ट गरिएको छ',
    expressDelivery: 'छिटो डेलिभरी',
    quickShipping: 'सबैभन्दा छिटो सम्भव ढुवानी समय',
    blogsEmptyTitle: 'हाल कुनै ब्लग उपलब्ध छैन',
    blogsEmptyDesc: 'नयाँ सामग्रीका लागि पछि फेरि हेर्नुहोस्',
    blogNotFound: 'ब्लग भेटिएन',
    blogLoadError: 'ब्लग लोड गर्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।',
    blogNotFoundDesc: 'तपाईंले खोजेको ब्लग उपलब्ध छैन वा हटाइएको छ।',
    backToBlogs: 'ब्लगतर्फ फर्कनुहोस्',
    editorialLabel: 'सम्पादकीय',
    minRead: 'मिनेट पढाइ',
    keyTakeaway: 'मुख्य निष्कर्ष',
    readingGuide: 'पढ्ने मार्गदर्शन',
    readingGuideDesc: 'न्यानो पेयसँग आरामले पढ्न उपयुक्त।',
    moreLikeThis: 'यस्तै अरू',
    picks: 'छनोट',
    contactHeroTitle: 'हाम्रो टोलीसँग सम्पर्क गर्नुहोस्',
    contactHeroSubtitle: 'हाम्रा उत्पादन वा सेवाबारे प्रश्न छन्? हामी यहाँ सहयोगका लागि छौं। तलका माध्यमबाट सम्पर्क गर्नुहोस्।',
    onlineSupport: 'अनलाइन समर्थन',
    email: 'इमेल',
    location: 'स्थान',
    contactOfficeHours: 'आइत-शुक्र, बिहान १० देखि बेलुका ६',
    contactCity: 'कावासोती, नवलपुर',
    contactArea: 'मुख्य बजार क्षेत्र',
    messageSentSuccess: 'सन्देश सफलतापूर्वक पठाइयो। हामी छिट्टै सम्पर्क गर्नेछौं।',
    sending: 'पठाउँदै...',
    quickResponseTitle: 'छिटो प्रतिक्रिया',
    quickResponseDesc: '२४ घण्टाभित्र जवाफ',
    secureCommunicationTitle: 'सुरक्षित सञ्चार',
    secureCommunicationDesc: 'तपाईंको डेटा सुरक्षित छ',
    nationwideSupportTitle: 'राष्ट्रिय स्तरको समर्थन',
    nationwideSupportDesc: 'नेपालभर सेवा',
    expertGuidanceTitle: 'विशेषज्ञ मार्गदर्शन',
    expertGuidanceDesc: 'समर्पित समर्थन टोली',
    contactFooter: '© 2026 Hamro Commerce • कावासोती, नवलपुर',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<'en' | 'ne'>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as 'en' | 'ne' | null;
    if (savedLanguage) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: 'en' | 'ne') => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
